In [ ]:
# Install required packages
!pip install pyscf ase matplotlib numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.2/51.2 MB 14.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 60.7 MB/s eta 0:00:00


In [ ]:
pip install geometric


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.0/386.0 kB 10.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for geometric: filename=geometric-1.1-py3-none-any.whl size=402087 sha256=0cfde2d4f172dfa39090c4cabaf101f9e70be0b2715354ea89a69a82077ecdc7
  Stored in directory: /root/.cache/pip/wheels/df/1e/9a/763451b0dfd8db47fc02239e33cdf138cbebdbea352bb0871b
Successfully built geometric


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from ase import Atoms
from ase.optimize import BFGS
from ase.constraints import FixBondLengths
from pyscf import gto, scf, dft, lib

In [ ]:
from pyscf import gto, dft
from pyscf.geomopt.geometric_solver import optimize

# ============================
# 1. Optimize NH3
# ============================
mol_nh3 = gto.Mole()
mol_nh3.atom = '''
N  0.0000   0.0000   0.0000
H  0.0000   0.9395   0.0000
H  0.8137  -0.4697   0.0000
H -0.8137  -0.4697   0.0000
'''
mol_nh3.basis = 'def2-TZVP'
mol_nh3.build()

mf = dft.RKS(mol_nh3)
mf.xc = 'b3lyp'

print("\nOptimizing NH3...")
mol_nh3_opt = optimize(mf)
print("Optimized NH3 geometry:\n", mol_nh3_opt.atom_coords())

# ============================
# 2. Optimize CO2
# ============================
mol_co2 = gto.Mole()
mol_co2.atom = '''
C  0.0000   0.0000   0.0000
O  1.1600   0.0000   0.0000
O -1.1600   0.0000   0.0000
'''
mol_co2.basis = 'def2-TZVP'
mol_co2.build()

mf = dft.RKS(mol_co2)
mf.xc = 'b3lyp'

print("\nOptimizing CO2...")
mol_co2_opt = optimize(mf)
print("Optimized CO2 geometry:\n", mol_co2_opt.atom_coords())

# ============================
# 3. Optimize NH3–CO2 Complex
# ============================
mol_complex = gto.Mole()
mol_complex.atom = '''
N   0.0000   0.0000   0.0000
H   0.0000   0.9395   0.0000
H   0.8137  -0.4697   0.0000
H  -0.8137  -0.4697   0.0000
C   3.0000   0.0000   0.0000
O   4.1600   0.0000   0.0000
O   1.8400   0.0000   0.0000
'''
mol_complex.basis = 'def2-TZVP'
mol_complex.build()

mf = dft.RKS(mol_complex)
mf.xc = 'b3lyp'

print("\nOptimizing NH3–CO2 complex...")
mol_complex_opt = optimize(mf)
print("Optimized NH3–CO2 complex geometry:\n", mol_complex_opt.atom_coords())


geometric-optimize called with the following command line:
/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py -f /root/.local/share/jupyter/runtime/kernel-4ecb077b-be94-4400-a893-f298fae25752.json

                                        ())))))))))))))))/                     
                                    ())))))))))))))))))))))))),                
                                *)))))))))))))))))))))))))))))))))             
                        #,    ()))))))))/                .)))))))))),          
                      #%%%%,  ())))))                        .))))))))*        
                      *%%%%%%,  ))              ..              ,))))))).      
                        *%%%%%%,         ***************/.        .)))))))     
                #%%/      (%%%%%%,    /*********************.       )))))))    
              .%%%%%%#      *%%%%%%,  *******/,     **********,      .))))))   
                .%%%%%%/      *%%%%%%,  **              ********    


Optimizing NH3...

Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N   0.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   H   0.000000   0.939500   0.000000    0.000000  0.000000  0.000000
   H   0.813700  -0.469700   0.000000    0.000000  0.000000  0.000000
   H  -0.813700  -0.469700   0.000000    0.000000  0.000000  0.000000


/usr/local/lib/python3.12/dist-packages/pyscf/dft/libxc.py:511: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '


converged SCF energy = -56.5683081931928
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0000000000     0.0000324850     0.0000000000
1 H     0.0000000000    -0.0659053535    -0.0000000000
2 H    -0.0570254013     0.0329351680     0.0000000000
3 H     0.0570254013     0.0329351680    -0.0000000000
----------------------------------------------
cycle 1: E = -56.5683081932  dE = -56.5683  norm(grad) = 0.114091


Step    0 : Gradient = 5.705e-02/6.591e-02 (rms/max) Energy = -56.5683081932
Hessian Eigenvalues: 4.50000e-02 5.00000e-02 5.00000e-02 ... 6.01188e-01 6.01188e-01 6.01271e-01



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N   0.000022   0.000054  -0.000000    0.000022  0.000054 -0.000000
   H  -0.000037   0.997556  -0.000000   -0.000037  0.058056 -0.000000
   H   0.863865  -0.498727  -0.000000    0.050165 -0.029027 -0.000000
   H  -0.863850  -0.498676   0.000000   -0.050150 -0.028976  0.000000
converged SCF energy = -56.5784746724703
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0000117014    -0.0000029961     0.0000000000
1 H    -0.0000096595     0.0000437939    -0.0000000000
2 H     0.0000340492    -0.0000268066    -0.0000000000
3 H    -0.0000360940    -0.0000168332     0.0000000000
----------------------------------------------
cycle 2: E = -56.5784746725  dE = -0.0101665  norm(grad) = 7.49746e-05


Step    1 : Displace = 5.021e-02/5.803e-02 (rms/max) Trust = 1.000e-01 (=) Grad = 3.749e-05/4.485e-05 (rms/max) E (change) = -56.5784746725 (-1.017e-02) Quality = 0.939
Hessian Eigenvalues: 4.50000e-02 5.00000e-02 5.00000e-02 ... 6.01187e-01 6.01235e-01 6.01608e-01



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.000014   0.000070  -0.000000   -0.000036  0.000017 -0.000000
   H   0.000025   0.997534  -0.000000    0.000062 -0.000022  0.000000
   H   0.863837  -0.498621  -0.000000   -0.000028  0.000106  0.000000
   H  -0.863848  -0.498656  -0.000000    0.000002  0.000020 -0.000000
converged SCF energy = -56.5784746779439
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0000052582    -0.0000075502     0.0000000000
1 H     0.0000063218     0.0000058110    -0.0000000000
2 H     0.0000085175     0.0000034051     0.0000000000
3 H    -0.0000095793    -0.0000045079    -0.0000000000
----------------------------------------------
cycle 3: E = -56.5784746779  dE = -5.47361e-09  norm(grad) = 1.88312e-05


Step    2 : Displace = 6.047e-05/8.087e-05 (rms/max) Trust = 1.414e-01 (+) Grad = 9.416e-06/1.059e-05 (rms/max) E (change) = -56.5784746779 (-5.474e-09) Quality = 0.929
Hessian Eigenvalues: 4.50000e-02 5.00000e-02 5.00000e-02 ... 6.01187e-01 6.01235e-01 6.01608e-01
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 17.456 seconds
geometric-optimize called with the following command line:
/usr/local/lib/python3.12/dist-

Optimized NH3 geometry:
 [[-2.59961561e-05  1.33118709e-04 -8.84525892e-15]
 [ 4.65597908e-05  1.88506586e+00 -1.63737658e-15]
 [ 1.63241624e+00 -9.42257331e-01 -1.13311690e-14]
 [-1.63243657e+00 -9.42322858e-01 -2.33744178e-16]]

Optimizing CO2...


> Initial / maximum trust radius (Angstrom): 0.100 / 0.300
> Convergence Criteria:
> Will converge when all 5 criteria are reached:
>  |Delta-E| < 1.00e-06
>  RMS-Grad  < 3.00e-04
>  Max-Grad  < 4.50e-04
>  RMS-Disp  < 1.20e-03
>  Max-Disp  < 1.80e-03
> === End Optimization Info ===



Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C   0.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   O   1.160000   0.000000   0.000000    0.000000  0.000000  0.000000
   O  -1.160000   0.000000   0.000000    0.000000  0.000000  0.000000
converged SCF energy = -188.669935659863
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 C     0.0000000000    -0.0000000000    -0.0000000000
1 O     0.0005684687     0.0000000000     0.0000000000
2 O    -0.0005684687     0.0000000000     0.0000000000
----------------------------------------------
cycle 1: E = -188.66993566  dE = -188.67  norm(grad) = 0.000803936


Step    0 : Gradient = 4.642e-04/5.685e-04 (rms/max) Energy = -188.6699356599
Hessian Eigenvalues: 5.00000e-02 5.00000e-02 5.00000e-02 ... 2.50000e-01 1.27794e+00 1.27794e+00



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   C  -0.000000   0.000000  -0.000000   -0.000000  0.000000 -0.000000
   O   1.159765  -0.000000  -0.000000   -0.000235 -0.000000 -0.000000
   O  -1.159765   0.000000  -0.000000    0.000235  0.000000 -0.000000
converged SCF energy = -188.669935950134
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 C     0.0000000000     0.0000000000     0.0000000000
1 O     0.0000620854     0.0000000000    -0.0000000000
2 O    -0.0000620854    -0.0000000000    -0.0000000000
----------------------------------------------
cycle 2: E = -188.66993595  dE = -2.9027e-07  norm(grad) = 8.7802e-05


Step    1 : Displace = 1.922e-04/2.354e-04 (rms/max) Trust = 1.000e-01 (=) Grad = 5.069e-05/6.209e-05 (rms/max) E (change) = -188.6699359501 (-2.903e-07) Quality = 1.148
Hessian Eigenvalues: 5.00000e-02 5.00000e-02 5.00000e-02 ... 2.50000e-01 1.27794e+00 1.27794e+00
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 29.119 seconds
geometric-optimize called with the following command line:
/usr/local/lib/python3.12/dist

Optimized CO2 geometry:
 [[-4.19154978e-13  1.20924090e-14 -2.55101188e-14]
 [ 2.19163747e+00 -2.47022359e-14 -5.41612869e-14]
 [-2.19163747e+00  3.44818543e-14 -7.83963794e-15]]

Optimizing NH3–CO2 complex...

Geometry optimization cycle 1
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N   0.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   H   0.000000   0.939500   0.000000    0.000000  0.000000  0.000000
   H   0.813700  -0.469700   0.000000    0.000000  0.000000  0.000000
   H  -0.813700  -0.469700   0.000000    0.000000  0.000000  0.000000
   C   3.000000   0.000000   0.000000    0.000000  0.000000  0.000000
   O   4.160000   0.000000   0.000000    0.000000  0.000000  0.000000
   O   1.840000   0.000000   0.000000    0.000000  0.000000  0.000000
converged SCF energy = -245.08361733253
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.1541155588     0.028904

Step    0 : Gradient = 1.265e-01/2.564e-01 (rms/max) Energy = -245.0836173325
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 3.17988e-02 ... 6.01271e-01 1.27794e+00 1.27794e+00



Geometry optimization cycle 2
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.078164   0.004803  -0.000000   -0.078164  0.004803 -0.000000
   H  -0.123335   0.959583  -0.000000   -0.123335  0.020083 -0.000000
   H   0.809257  -0.436489  -0.000000   -0.004443  0.033211 -0.000000
   H  -0.885482  -0.511575  -0.000000   -0.071782 -0.041875 -0.000000
   C   3.095692  -0.004795   0.000000    0.095692 -0.004795  0.000000
   O   4.254098  -0.045590   0.000000    0.094098 -0.045590  0.000000
   O   1.927940   0.034171   0.000000    0.087940  0.034171  0.000000
converged SCF energy = -245.150853043434
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0580909465     0.0412228792     0.0000000000
1 H     0.0033837566    -0.0456924975     0.0000000000
2 H     0.0757314997     0.0251519363    -0.0000000000
3 H     0.0457745620     0.0154892118    -0.0000000000
4 C    -0.0192365431  

Step    1 : Displace = 9.164e-02/1.250e-01 (rms/max) Trust = 1.000e-01 (=) Grad = 8.160e-02/1.741e-01 (rms/max) E (change) = -245.1508530434 (-6.724e-02) Quality = 0.855
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 3.17988e-02 ... 8.88305e-01 1.27521e+00 1.29012e+00



Geometry optimization cycle 3
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.172136  -0.016011   0.000000   -0.093973 -0.020814  0.000000
   H  -0.244565   0.976247   0.000000   -0.121229  0.016665  0.000000
   H   0.759803  -0.388391  -0.000000   -0.049454  0.048098 -0.000000
   H  -0.998859  -0.562972   0.000000   -0.113378 -0.051397  0.000000
   C   3.222991  -0.001182  -0.000000    0.127299  0.003613 -0.000000
   O   4.372576  -0.105499   0.000000    0.118478 -0.059910  0.000000
   O   2.059898   0.097684  -0.000000    0.131958  0.063513 -0.000000
converged SCF energy = -245.206150491972
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0249532348     0.0088322184     0.0000000000
1 H     0.0039530323    -0.0044314038    -0.0000000000
2 H     0.0497929496     0.0113549889    -0.0000000000
3 H     0.0075054021     0.0015463240    -0.0000000000
4 C     0.0030696777  

Step    2 : Displace = 1.194e-01/1.465e-01 (rms/max) Trust = 1.414e-01 (+) Grad = 3.978e-02/8.747e-02 (rms/max) E (change) = -245.2061504920 (-5.530e-02) Quality = 1.368
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 3.17988e-02 ... 7.65552e-01 1.27828e+00 1.28696e+00



Geometry optimization cycle 4
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.237343   0.008983   0.000000   -0.065207  0.024993 -0.000000
   H  -0.476069   0.983290   0.000000   -0.231504  0.007043  0.000000
   H   0.708067  -0.320310  -0.000000   -0.051737  0.068081 -0.000000
   H  -1.013277  -0.617851   0.000000   -0.014417 -0.054879  0.000000
   C   3.341874  -0.017027  -0.000000    0.118884 -0.015845 -0.000000
   O   4.484638  -0.185138   0.000000    0.112063 -0.079639  0.000000
   O   2.191110   0.147743  -0.000000    0.131211  0.050059 -0.000000
converged SCF energy = -245.22825847464
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0237004505     0.0043547149     0.0000000000
1 H    -0.0073055409     0.0023878018    -0.0000000000
2 H     0.0268153906    -0.0020848924    -0.0000000000
3 H     0.0007218247     0.0026724716    -0.0000000000
4 C     0.0005350010   

Step    3 : Displace = 1.320e-01/2.315e-01 (rms/max) Trust = 2.000e-01 (+) Grad = 2.103e-02/4.135e-02 (rms/max) E (change) = -245.2282584746 (-2.211e-02) Quality = 1.397
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 3.17988e-02 ... 7.32586e-01 1.27822e+00 1.28535e+00



Geometry optimization cycle 5
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.337103  -0.015080  -0.000000   -0.099760 -0.024062 -0.000000
   H  -0.493178   0.973167   0.000000   -0.017110 -0.010123  0.000000
   H   0.620749  -0.277190  -0.000000   -0.087318  0.043120 -0.000000
   H  -1.107284  -0.654388   0.000000   -0.094007 -0.036537  0.000000
   C   3.439025  -0.009858  -0.000000    0.097151  0.007169 -0.000000
   O   4.579511  -0.208783   0.000000    0.094872 -0.023645  0.000000
   O   2.297279   0.191249  -0.000000    0.106170  0.043506 -0.000000
converged SCF energy = -245.239903248214
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0080725596    -0.0064765680     0.0000000000
1 H     0.0065785626     0.0018857164    -0.0000000000
2 H     0.0093976853     0.0103433204    -0.0000000000
3 H    -0.0040331251    -0.0023984159    -0.0000000000
4 C    -0.0054987346  

Step    4 : Displace = 9.470e-02/1.146e-01 (rms/max) Trust = 2.828e-01 (+) Grad = 9.491e-03/1.512e-02 (rms/max) E (change) = -245.2399032482 (-1.164e-02) Quality = 1.235
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 3.17988e-02 ... 7.18165e-01 1.27922e+00 1.28338e+00



Geometry optimization cycle 6
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.407940   0.023035  -0.000000   -0.070837  0.038115 -0.000000
   H  -0.719843   0.972463   0.000000   -0.226665 -0.000703  0.000000
   H   0.559490  -0.207274  -0.000000   -0.061259  0.069916 -0.000000
   H  -1.093873  -0.702340   0.000000    0.013411 -0.047952  0.000000
   C   3.553788  -0.030569  -0.000000    0.114763 -0.020711 -0.000000
   O   4.686370  -0.276759   0.000000    0.106859 -0.067975 -0.000000
   O   2.421671   0.220170  -0.000000    0.124392  0.028921 -0.000000
converged SCF energy = -245.245498601011
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0097039060     0.0026294431     0.0000000000
1 H    -0.0028238641     0.0008858218    -0.0000000000
2 H     0.0025190996    -0.0021205781    -0.0000000000
3 H     0.0002148756    -0.0003301682    -0.0000000000
4 C    -0.0051555822  

Step    5 : Displace = 1.281e-01/2.274e-01 (rms/max) Trust = 3.000e-01 (+) Grad = 5.265e-03/1.005e-02 (rms/max) E (change) = -245.2454986010 (-5.595e-03) Quality = 1.265
Hessian Eigenvalues: 2.30000e-02 2.30000e-02 3.17988e-02 ... 7.07152e-01 1.27817e+00 1.28178e+00



Geometry optimization cycle 7
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.475406   0.027052  -0.000000   -0.067467  0.004017 -0.000000
   H  -0.808601   0.966733   0.000000   -0.088758 -0.005730  0.000000
   H   0.502292  -0.167264  -0.000000   -0.057198  0.040011 -0.000000
   H  -1.129542  -0.725445   0.000000   -0.035668 -0.023105  0.000000
   C   3.637364  -0.035364  -0.000000    0.083577 -0.004795 -0.000000
   O   4.763839  -0.307046   0.000000    0.077469 -0.030287 -0.000000
   O   2.510264   0.239755  -0.000000    0.088593  0.019585 -0.000000
converged SCF energy = -245.247570815237
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0025996235     0.0030566602     0.0000000000
1 H    -0.0006647193    -0.0005956091    -0.0000000000
2 H     0.0017402618    -0.0019438818    -0.0000000000
3 H     0.0012375416    -0.0001286977    -0.0000000000
4 C    -0.0023036790  

Step    6 : Displace = 7.683e-02/9.067e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 2.550e-03/4.013e-03 (rms/max) E (change) = -245.2475708152 (-2.072e-03) Quality = 1.456
Hessian Eigenvalues: 1.85875e-02 2.30000e-02 2.30000e-02 ... 7.01340e-01 1.27622e+00 1.28198e+00



Geometry optimization cycle 8
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.542551   0.029681  -0.000000   -0.067145  0.002629 -0.000000
   H  -0.900105   0.959985   0.000000   -0.091505 -0.006748  0.000000
   H   0.443757  -0.124562  -0.000000   -0.058535  0.042701 -0.000000
   H  -1.169267  -0.745756   0.000000   -0.039725 -0.020310  0.000000
   C   3.723243  -0.041193  -0.000000    0.085879 -0.005829 -0.000000
   O   4.843389  -0.336561   0.000000    0.079550 -0.029515  0.000000
   O   2.601535   0.256279  -0.000000    0.091271  0.016524 -0.000000
converged SCF energy = -245.248606464083
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0007736290     0.0017155920     0.0000000000
1 H     0.0006224829    -0.0005568295    -0.0000000000
2 H     0.0014506959    -0.0008711872    -0.0000000000
3 H     0.0009170847    -0.0002191751    -0.0000000000
4 C    -0.0002688914  

Step    7 : Displace = 7.872e-02/9.279e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 1.317e-03/2.016e-03 (rms/max) E (change) = -245.2486064641 (-1.036e-03) Quality = 1.387
Hessian Eigenvalues: 1.02507e-02 2.30000e-02 2.30000e-02 ... 7.00884e-01 1.27697e+00 1.28197e+00



Geometry optimization cycle 9
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.596075   0.034363  -0.000000   -0.053523  0.004682 -0.000000
   H  -0.986374   0.951935   0.000000   -0.086269 -0.008050  0.000000
   H   0.395292  -0.084248  -0.000000   -0.048464  0.040314 -0.000000
   H  -1.196524  -0.761891   0.000000   -0.027258 -0.016136  0.000000
   C   3.794806  -0.048220  -0.000000    0.071562 -0.007026  0.000000
   O   4.909956  -0.362050   0.000000    0.066567 -0.025490  0.000000
   O   2.678093   0.267312  -0.000000    0.076558  0.011033 -0.000000
converged SCF energy = -245.248999913729
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0006545171     0.0007955493     0.0000000000
1 H     0.0003903260    -0.0001777222    -0.0000000000
2 H     0.0008233279    -0.0005213558    -0.0000000000
3 H     0.0004097934    -0.0001457886    -0.0000000000
4 C     0.0001390429  

Step    8 : Displace = 6.719e-02/8.697e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 6.944e-04/1.030e-03 (rms/max) E (change) = -245.2489999137 (-3.934e-04) Quality = 1.405
Hessian Eigenvalues: 5.64563e-03 2.30000e-02 2.30000e-02 ... 7.00913e-01 1.27719e+00 1.28196e+00



Geometry optimization cycle 10
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.639771   0.038984  -0.000000   -0.043696  0.004621 -0.000000
   H  -1.060543   0.943339   0.000000   -0.074169 -0.008596  0.000000
   H   0.354589  -0.047985  -0.000000   -0.040703  0.036263 -0.000000
   H  -1.215650  -0.775355   0.000000   -0.019125 -0.013464  0.000000
   C   3.853733  -0.054762  -0.000000    0.058927 -0.006542  0.000000
   O   4.965102  -0.382319   0.000000    0.055146 -0.020268  0.000000
   O   2.741135   0.274541  -0.000000    0.063042  0.007229 -0.000000
converged SCF energy = -245.24914615103
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0000146098     0.0002985126     0.0000000000
1 H     0.0000492987    -0.0000127341    -0.0000000000
2 H     0.0002149019    -0.0003589542    -0.0000000000
3 H     0.0000808127    -0.0000138159    -0.0000000000
4 C    -0.0000162150  

Step    9 : Displace = 5.608e-02/7.481e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 2.378e-04/4.184e-04 (rms/max) E (change) = -245.2491461510 (-1.462e-04) Quality = 1.370
Hessian Eigenvalues: 3.34178e-03 2.30000e-02 2.30000e-02 ... 7.00739e-01 1.27723e+00 1.28192e+00



Geometry optimization cycle 11
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.670319   0.042218  -0.000000   -0.030548  0.003234 -0.000000
   H  -1.112762   0.936246   0.000000   -0.052219 -0.007093  0.000000
   H   0.325649  -0.021243  -0.000000   -0.028940  0.026742 -0.000000
   H  -1.226996  -0.785378   0.000000   -0.011346 -0.010023  0.000000
   C   3.894447  -0.059329   0.000000    0.040714 -0.004567  0.000000
   O   5.003462  -0.395146   0.000000    0.038360 -0.012828  0.000000
   O   2.784418   0.278295  -0.000000    0.043283  0.003754 -0.000000
converged SCF energy = -245.249187913461
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0002527258     0.0001139054     0.0000000000
1 H    -0.0000443235     0.0000094406    -0.0000000000
2 H    -0.0001002193    -0.0002642983    -0.0000000000
3 H    -0.0000236316     0.0000470194    -0.0000000000
4 C    -0.0001129443 

Step   10 : Displace = 3.911e-02/5.251e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 1.740e-04/2.827e-04 (rms/max) E (change) = -245.2491879135 (-4.176e-05) Quality = 1.350
Hessian Eigenvalues: 2.14622e-03 2.30000e-02 2.30000e-02 ... 7.00287e-01 1.27734e+00 1.28186e+00



Geometry optimization cycle 12
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.687976   0.043971  -0.000000   -0.017657  0.001753 -0.000000
   H  -1.143459   0.931394   0.000000   -0.030697 -0.004852  0.000000
   H   0.308799  -0.004936  -0.000000   -0.016850  0.016307 -0.000000
   H  -1.232146  -0.791890   0.000000   -0.005150 -0.006512  0.000000
   C   3.917841  -0.061751   0.000000    0.023394 -0.002422  0.000000
   O   5.025752  -0.401325   0.000000    0.022290 -0.006179  0.000000
   O   2.808973   0.279600  -0.000000    0.024555  0.001305 -0.000000
converged SCF energy = -245.24919718442
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0001981607     0.0000970574     0.0000000000
1 H    -0.0000255481    -0.0000048433    -0.0000000000
2 H    -0.0001860847    -0.0002340277    -0.0000000000
3 H    -0.0000162859     0.0000490741    -0.0000000000
4 C    -0.0000995469  

Step   11 : Displace = 2.265e-02/3.074e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 1.703e-04/2.990e-04 (rms/max) E (change) = -245.2491971844 (-9.271e-06) Quality = 1.345
Hessian Eigenvalues: 1.59658e-03 2.30000e-02 2.30000e-02 ... 6.97113e-01 1.27698e+00 1.28177e+00



Geometry optimization cycle 13
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.695518   0.044508  -0.000000   -0.007542  0.000536 -0.000000
   H  -1.157248   0.928662   0.000000   -0.013788 -0.002732  0.000000
   H   0.301602   0.002643  -0.000000   -0.007197  0.007580 -0.000000
   H  -1.233433  -0.795386   0.000000   -0.001288 -0.003496  0.000000
   C   3.927749  -0.062508   0.000000    0.009908 -0.000757  0.000000
   O   5.035478  -0.402705   0.000000    0.009725 -0.001380  0.000000
   O   2.819061   0.279423  -0.000000    0.010088 -0.000178 -0.000000
converged SCF energy = -245.249199014047
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0001126437     0.0001186248     0.0000000000
1 H     0.0000018947    -0.0000162015    -0.0000000000
2 H    -0.0001925068    -0.0002307903    -0.0000000000
3 H     0.0000079528     0.0000374229    -0.0000000000
4 C    -0.0000740765 

Step   12 : Displace = 9.788e-03/1.361e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 1.612e-04/3.005e-04 (rms/max) E (change) = -245.2491990140 (-1.830e-06) Quality = 1.479
Hessian Eigenvalues: 1.38010e-03 2.30000e-02 2.30000e-02 ... 6.85108e-01 1.27579e+00 1.28159e+00



Geometry optimization cycle 14
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.700378   0.044529  -0.000000   -0.004860  0.000021 -0.000000
   H  -1.167130   0.926014   0.000000   -0.009882 -0.002648  0.000000
   H   0.296990   0.008332  -0.000000   -0.004612  0.005688 -0.000000
   H  -1.233226  -0.798585   0.000000    0.000207 -0.003199  0.000000
   C   3.934087  -0.062614   0.000000    0.006338 -0.000106  0.000000
   O   5.042099  -0.401887   0.000000    0.006621  0.000818  0.000000
   O   2.825098   0.278346  -0.000000    0.006038 -0.001077 -0.000000
converged SCF energy = -245.249200256007
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0000382368     0.0001410267     0.0000000000
1 H     0.0000250014    -0.0000249074    -0.0000000000
2 H    -0.0001864868    -0.0002306893    -0.0000000000
3 H     0.0000301337     0.0000257991    -0.0000000000
4 C    -0.0000336458 

Step   13 : Displace = 6.591e-03/9.501e-03 (rms/max) Trust = 3.000e-01 (=) Grad = 1.568e-04/2.966e-04 (rms/max) E (change) = -245.2492002560 (-1.242e-06) Quality = 1.558
Hessian Eigenvalues: 1.31865e-03 2.30000e-02 2.30000e-02 ... 6.75584e-01 1.27625e+00 1.28151e+00



Geometry optimization cycle 15
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.708238   0.043756  -0.000000   -0.007860 -0.000773 -0.000000
   H  -1.185633   0.919472   0.000000   -0.018504 -0.006542  0.000000
   H   0.289543   0.019584  -0.000000   -0.007447  0.011252 -0.000000
   H  -1.230365  -0.806034   0.000000    0.002861 -0.007450  0.000000
   C   3.944275  -0.061864   0.000000    0.010187  0.000750  0.000000
   O   5.053726  -0.396399   0.000000    0.011627  0.005488  0.000000
   O   2.833812   0.274249  -0.000000    0.008713 -0.004096 -0.000000
converged SCF energy = -245.249203019215
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0000904009     0.0001787867     0.0000000001
1 H     0.0000642032    -0.0000385899    -0.0000000000
2 H    -0.0001685373    -0.0002275624    -0.0000000000
3 H     0.0000686991     0.0000043964    -0.0000000000
4 C     0.0000113489 

Step   14 : Displace = 1.170e-02/1.726e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 1.641e-04/2.832e-04 (rms/max) E (change) = -245.2492030192 (-2.763e-06) Quality = 1.395
Hessian Eigenvalues: 1.28839e-03 1.65855e-02 2.30000e-02 ... 6.74716e-01 1.27678e+00 1.28148e+00



Geometry optimization cycle 16
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.717678   0.041004  -0.000000   -0.009439 -0.002751 -0.000000
   H  -1.213742   0.906221   0.000000   -0.028109 -0.013251  0.000000
   H   0.280457   0.038048  -0.000000   -0.009086  0.018464 -0.000000
   H  -1.220940  -0.820089   0.000000    0.009426 -0.014054  0.000000
   C   3.956416  -0.058904   0.000000    0.012141  0.002960  0.000000
   O   5.069718  -0.380379   0.000000    0.015992  0.016020  0.000000
   O   2.842035   0.263946  -0.000000    0.008224 -0.010303 -0.000000
converged SCF energy = -245.249208295076
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0002460907     0.0002129834     0.0000000003
1 H     0.0001100362    -0.0000539866    -0.0000000001
2 H    -0.0001375918    -0.0002112093    -0.0000000001
3 H     0.0001151094    -0.0000188182    -0.0000000001
4 C     0.0000731221 

Step   15 : Displace = 1.738e-02/2.526e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 1.896e-04/3.255e-04 (rms/max) E (change) = -245.2492082951 (-5.276e-06) Quality = 1.351
Hessian Eigenvalues: 1.31092e-03 7.29127e-03 2.30000e-02 ... 6.75418e-01 1.27718e+00 1.28144e+00



Geometry optimization cycle 17
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.724164   0.034967  -0.000000   -0.006486 -0.006037 -0.000000
   H  -1.247198   0.884114   0.000000   -0.033456 -0.022107  0.000000
   H   0.273637   0.062999  -0.000000   -0.006820  0.024951 -0.000000
   H  -1.199852  -0.841667   0.000000    0.021088 -0.021578  0.000000
   C   3.964557  -0.052199   0.000000    0.008142  0.006705  0.000000
   O   5.085074  -0.347513   0.000000    0.015356  0.032866  0.000000
   O   2.842862   0.244147  -0.000000    0.000826 -0.019800 -0.000000
converged SCF energy = -245.249217521363
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0003467785     0.0002084300     0.0000000012
1 H     0.0001359749    -0.0000606350    -0.0000000004
2 H    -0.0001017904    -0.0001665595    -0.0000000004
3 H     0.0001412527    -0.0000324618    -0.0000000004
4 C     0.0001142421 

Step   16 : Displace = 2.234e-02/3.239e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 2.033e-04/4.046e-04 (rms/max) E (change) = -245.2492175214 (-9.226e-06) Quality = 1.435
Hessian Eigenvalues: 1.43368e-03 3.54070e-03 2.30000e-02 ... 6.75631e-01 1.27695e+00 1.28142e+00



Geometry optimization cycle 18
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.720081   0.027576  -0.000000    0.004083 -0.007391 -0.000000
   H  -1.265569   0.862927   0.000000   -0.018371 -0.021187  0.000000
   H   0.276996   0.081459  -0.000000    0.003359  0.018460 -0.000000
   H  -1.173044  -0.861410   0.000000    0.026807 -0.019743  0.000000
   C   3.958841  -0.043831   0.000000   -0.005716  0.008368  0.000000
   O   5.087503  -0.308212   0.000000    0.002428  0.039300  0.000000
   O   2.828889   0.221191  -0.000000   -0.013973 -0.022955 -0.000000
converged SCF energy = -245.249228193372
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0002652379     0.0001350369     0.0000000033
1 H    -0.0000720681     0.0002275859    -0.0000000011
2 H     0.0002318140    -0.0000856932    -0.0000000011
3 H    -0.0000332309    -0.0003077994    -0.0000000011
4 C     0.0001189193 

Step   17 : Displace = 2.040e-02/3.442e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 5.110e-04/8.771e-04 (rms/max) E (change) = -245.2492281934 (-1.067e-05) Quality = 1.953
Hessian Eigenvalues: 1.30882e-03 2.19942e-03 2.30000e-02 ... 6.76027e-01 1.27660e+00 1.32789e+00



Geometry optimization cycle 19
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.708605   0.022615  -0.000000    0.011475 -0.004961  0.000000
   H  -1.263085   0.851977   0.000000    0.002484 -0.010949  0.000000
   H   0.287776   0.086927   0.000001    0.010780  0.005468  0.000001
   H  -1.152642  -0.870773  -0.000001    0.020402 -0.009363 -0.000001
   C   3.943494  -0.038158  -0.000000   -0.015347  0.005672 -0.000000
   O   5.076844  -0.281531  -0.000000   -0.010659  0.026682 -0.000000
   O   2.808808   0.205665   0.000000   -0.020081 -0.015527  0.000000
converged SCF energy = -245.249236372791
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0001507706     0.0000566969     0.0000000067
1 H    -0.0000777408     0.0001671441    -0.0000000024
2 H     0.0002028110    -0.0000338622    -0.0000000015
3 H    -0.0000492982    -0.0002086545    -0.0000000026
4 C     0.0000700718 

Step   18 : Displace = 1.712e-02/2.834e-02 (rms/max) Trust = 3.000e-01 (=) Grad = 4.776e-04/8.543e-04 (rms/max) E (change) = -245.2492363728 (-8.179e-06) Quality = -0.000
Failed inverse iteration - checking coordinate system
Internal coordinate system may have changed
-- Added: --
Translation-X 1-4
Translation-X 5-7
Translation-Y 1-4
Translation-Y 5-7
Translation-Z 1-4
Translation-Z 5-7
Rotation-A 1-4
Rotation-A 5-7
Rotation-B 1-4
Rotation-B 5-7
Rotation-C 1-4
Rotation-C 5-7
-- Deleted: --
Distance 3-7
Angle 1-3-7
Angle 3-7-5
Dihedral 2-1-3-7
Dihedral 4-1-3-7
Dihedral 1-3-7-5
Translation-X 1-7
Translation-Y 1-7
Translation-Z 1-7
Rotation-A 1-7
Rotation-B 1-7
Rotation-C 1-7
Refreshing coordinate system and resetting rotations
Updating Hessian using 12 steps from history
Hessian Eigenvalues: 1.45413e-03 2.50529e-03 4.50000e-02 ... 6.01558e-01 1.27749e+00 1.28064e+00



Geometry optimization cycle 20
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.701278   0.021664  -0.000000    0.007328 -0.000951 -0.000000
   H  -1.254683   0.851548   0.000000    0.008402 -0.000429  0.000000
   H   0.294950   0.085057   0.000001    0.007174 -0.001870  0.000000
   H  -1.146702  -0.870828  -0.000001    0.005940 -0.000055 -0.000000
   C   3.933934  -0.037132  -0.000000   -0.009561  0.001027 -0.000000
   O   5.067878  -0.276029  -0.000001   -0.008965  0.005501 -0.000000
   O   2.798688   0.202384   0.000000   -0.010120 -0.003281  0.000000
converged SCF energy = -245.249239024312
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N    -0.0000593722    -0.0000215532     0.0000000167
1 H     0.0000164508     0.0000296914    -0.0000000057
2 H     0.0000288689     0.0000097685    -0.0000000045
3 H    -0.0000214448    -0.0000342875    -0.0000000060
4 C     0.0000329702 

Step   19 : Displace = 8.640e-03/1.081e-02 (rms/max) Trust = 8.562e-03 (-) Grad = 7.663e-05/1.271e-04 (rms/max) E (change) = -245.2492390243 (-2.652e-06) Quality = 1.249
Hessian Eigenvalues: 1.50569e-03 2.50825e-03 4.50000e-02 ... 6.01568e-01 1.18983e+00 1.27832e+00



Geometry optimization cycle 21
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.697095   0.021953  -0.000000    0.004183  0.000289 -0.000000
   H  -1.248603   0.853069   0.000000    0.006079  0.001521  0.000000
   H   0.299245   0.082609   0.000001    0.004295 -0.002447  0.000000
   H  -1.144924  -0.869280  -0.000001    0.001778  0.001548 -0.000000
   C   3.928599  -0.037292  -0.000000   -0.005335 -0.000160 -0.000000
   O   5.062418  -0.276391  -0.000001   -0.005460 -0.000362 -0.000000
   O   2.793508   0.202572   0.000001   -0.005180  0.000188  0.000000
converged SCF energy = -245.249239302679
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0000108976     0.0000042503     0.0000000444
1 H    -0.0000090662    -0.0000149143    -0.0000000151
2 H    -0.0000044817    -0.0000285386    -0.0000000133
3 H    -0.0000099421     0.0000223527    -0.0000000153
4 C     0.0000050811 

Step   20 : Displace = 4.909e-03/5.830e-03 (rms/max) Trust = 1.211e-02 (+) Grad = 2.503e-05/3.527e-05 (rms/max) E (change) = -245.2492393027 (-2.784e-07) Quality = 0.940
Hessian Eigenvalues: 1.34831e-03 2.70445e-03 3.92582e-02 ... 6.02299e-01 1.22553e+00 1.27838e+00



Geometry optimization cycle 22
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.696367   0.022570  -0.000001    0.000728  0.000617 -0.000000
   H  -1.246363   0.854684   0.000000    0.002240  0.001614  0.000000
   H   0.300042   0.081836   0.000001    0.000797 -0.000774  0.000000
   H  -1.145655  -0.867934  -0.000001   -0.000731  0.001346  0.000000
   C   3.927724  -0.038014  -0.000000   -0.000874 -0.000722  0.000000
   O   5.061027  -0.279495  -0.000001   -0.001391 -0.003104 -0.000000
   O   2.793167   0.204302   0.000001   -0.000341  0.001730  0.000000
converged SCF energy = -245.249239179862
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0000059134    -0.0000266053     0.0000001049
1 H     0.0000219008    -0.0000033949    -0.0000000353
2 H    -0.0000217533     0.0000004212    -0.0000000328
3 H    -0.0000160273     0.0000118793    -0.0000000357
4 C    -0.0000066415 

Step   21 : Displace = 1.546e-03/2.459e-03 (rms/max) Trust = 1.712e-02 (+) Grad = 3.550e-05/6.125e-05 (rms/max) E (change) = -245.2492391799 (+1.228e-07) Quality = -1.969
Not rejecting step - energy change meets convergence criteria
Hessian Eigenvalues: 6.90255e-04 2.97876e-03 1.41070e-02 ... 6.13540e-01 1.24260e+00 1.27884e+00



Geometry optimization cycle 23
Cartesian coordinates (Angstrom)
 Atom        New coordinates             dX        dY        dZ
   N  -0.696112   0.022979  -0.000002    0.000255  0.000409 -0.000001
   H  -1.246638   0.854750   0.000001   -0.000275  0.000066  0.000000
   H   0.300257   0.082913   0.000002    0.000215  0.001077  0.000000
   H  -1.144796  -0.867841  -0.000001    0.000860  0.000093  0.000000
   C   3.927515  -0.038413  -0.000000   -0.000209 -0.000399  0.000000
   O   5.060579  -0.281039  -0.000001   -0.000448 -0.001544 -0.000000
   O   2.793208   0.205105   0.000001    0.000041  0.000803  0.000000
converged SCF energy = -245.249239206262
--------------- RKS_Scanner gradients ---------------
         x                y                z
0 N     0.0000072112    -0.0000255710     0.0000002488
1 H     0.0000233932     0.0000040657    -0.0000000834
2 H    -0.0000229214     0.0000026285    -0.0000000792
3 H    -0.0000171031     0.0000013877    -0.0000000842
4 C    -0.0000079458 

Step   22 : Displace = 7.963e-04/1.085e-03 (rms/max) Trust = 7.731e-04 (-) Grad = 2.931e-05/4.493e-05 (rms/max) E (change) = -245.2492392063 (-2.640e-08) Quality = 0.254
Hessian Eigenvalues: 6.90255e-04 2.97876e-03 1.41070e-02 ... 6.13540e-01 1.24260e+00 1.27884e+00
Converged! =D

    #==========================================================================#
    #| If this code has benefited your research, please support us by citing: |#
    #|                                                                        |#
    #| Wang, L.-P.; Song, C.C. (2016) "Geometry optimization made simple with |#
    #| translation and rotation coordinates", J. Chem, Phys. 144, 214108.     |#
    #| http://dx.doi.org/10.1063/1.4952956                                    |#
    #==========================================================================#
    Time elapsed since start of run_optimizer: 845.522 seconds


Optimized NH3–CO2 complex geometry:
 [[-1.31546087e+00  4.34243162e-02 -3.18233251e-06]
 [-2.35580402e+00  1.61524277e+00  1.20908114e-06]
 [ 5.67402761e-01  1.56682710e-01  3.07777274e-06]
 [-2.16335028e+00 -1.63998087e+00 -9.97482720e-07]
 [ 7.42192727e+00 -7.25899561e-02 -6.20951145e-08]
 [ 9.56310744e+00 -5.31086863e-01 -1.27148107e-06]
 [ 5.27839818e+00  3.87592650e-01  1.16947685e-06]]


In [ ]:
# Define the reaction coordinate: distance between N and C atoms
def create_molecule(n_c_distance):
    # NH₃ molecule
    nh3 = Atoms('NH3',
                positions=[(0.0000, 0.0000, 0.0000),
                          (0.0000, 0.9395, 0.0000),
                          (0.8137, -0.4697, 0.0000),
                          (-0.8137, -0.4697, 0.0000)])

    # CO₂ molecule (aligned along x-axis)
    co2 = Atoms('CO2',
                positions=[(n_c_distance, 0.0000, 0.0000),
                          (n_c_distance + 1.1600, 0.0000, 0.0000),
                          (n_c_distance - 1.1600, 0.0000, 0.0000)])

    # Combine molecules
    system = nh3 + co2
    return system

# Set up DFT calculation
def calculate_energy(atoms):
    # Convert ASE atoms to PySCF format
    positions = atoms.get_positions()
    symbols = atoms.get_chemical_symbols()
    atom_str = []
    for i, sym in enumerate(symbols):
        atom_str.append(f"{sym} {positions[i][0]} {positions[i][1]} {positions[i][2]}")

    # Create molecule object
    mol = gto.M(atom=atom_str, basis = 'def2-TZVP')  # Using smaller basis for speed

    # Perform DFT calculation
    mf = dft.RKS(mol)
    mf.xc = 'b3lyp'
    energy = mf.kernel()

    return energy

# Perform PES scan
n_c_distances = np.linspace(1.8, 3.2, 8)  # Reduced points for faster computation
energies = []

print("Starting PES scan...")
for i, dist in enumerate(n_c_distances):
    print(f"Step {i+1}/{len(n_c_distances)}: N-C distance = {dist:.2f} Å")

    # Create initial geometry
    system = create_molecule(dist)

    # Calculate energy directly without optimization
    try:
        energy = calculate_energy(system)
        energies.append(energy)
        print(f"  Energy = {energy:.6f} Hartree")
    except Exception as e:
        print(f"  Calculation failed: {e}")
        energies.append(np.nan)

print("PES scan completed!")

Starting PES scan...
Step 1/8: N-C distance = 1.80 Å
converged SCF energy = -240.844828971283
  Energy = -240.844829 Hartree
Step 2/8: N-C distance = 2.00 Å
converged SCF energy = -242.655750155488
  Energy = -242.655750 Hartree
Step 3/8: N-C distance = 2.20 Å
converged SCF energy = -243.537346495116
  Energy = -243.537346 Hartree
Step 4/8: N-C distance = 2.40 Å
converged SCF energy = -244.159866689913
  Energy = -244.159867 Hartree
Step 5/8: N-C distance = 2.60 Å
converged SCF energy = -244.637576233054
  Energy = -244.637576 Hartree
Step 6/8: N-C distance = 2.80 Å
converged SCF energy = -244.927046045638
  Energy = -244.927046 Hartree
Step 7/8: N-C distance = 3.00 Å
converged SCF energy = -245.08361733253
  Energy = -245.083617 Hartree
Step 8/8: N-C distance = 3.20 Å
converged SCF energy = -245.164433307443
  Energy = -245.164433 Hartree
PES scan completed!


In [ ]:
import numpy as np
from ase import Atoms
from pyscf import gto, dft
import matplotlib.pyplot as plt

# ===== Helper function to calculate energy using PySCF =====
def calculate_energy(atoms, basis='def2-TZVP'):
    positions = atoms.get_positions()
    symbols = atoms.get_chemical_symbols()
    atom_str = []
    for i, sym in enumerate(symbols):
        atom_str.append(f"{sym} {positions[i][0]} {positions[i][1]} {positions[i][2]}")

    mol = gto.M(atom=atom_str, basis=basis)
    mf = dft.RKS(mol)
    mf.xc = 'b3lyp'
    energy = mf.kernel()
    return energy

# ===== Define molecules =====
# NH3 geometry
nh3 = Atoms('NH3',
            positions=[(0.0000, 0.0000, 0.0000),
                      (0.0000, 0.9395, 0.0000),
                      (0.8137, -0.4697, 0.0000),
                      (-0.8137, -0.4697, 0.0000)])

# CO2 geometry (linear along x-axis, centered at 0)
co2 = Atoms('CO2',
            positions=[(0.0000, 0.0000, 0.0000),
                      (1.1600, 0.0000, 0.0000),
                      (-1.1600, 0.0000, 0.0000)])

# ===== Compute isolated molecule energies =====
print("Computing isolated molecule energies...")
E_NH3 = calculate_energy(nh3)
E_CO2 = calculate_energy(co2)
print(f"Energy NH3 = {E_NH3:.6f} Hartree")
print(f"Energy CO2 = {E_CO2:.6f} Hartree")

# ===== Function to build NH3 + CO2 system with variable N-C distance =====
def create_complex(n_c_distance):
    # NH3 at origin (same as above)
    nh3 = Atoms('NH3',
                positions=[(0.0000, 0.0000, 0.0000),
                          (0.0000, 0.9395, 0.0000),
                          (0.8137, -0.4697, 0.0000),
                          (-0.8137, -0.4697, 0.0000)])
    # CO2 shifted along x-axis
    co2 = Atoms('CO2',
                positions=[(n_c_distance, 0.0000, 0.0000),
                          (n_c_distance + 1.1600, 0.0000, 0.0000),
                          (n_c_distance - 1.1600, 0.0000, 0.0000)])
    return nh3 + co2

# ===== PES scan for binding energy =====
n_c_distances = np.linspace(1.8, 3.2, 8)
binding_energies = []

print("\nStarting PES scan for binding energies...")
for dist in n_c_distances:
    system = create_complex(dist)
    E_complex = calculate_energy(system)
    # Binding energy = E_complex - (E_NH3 + E_CO2)
    E_bind = E_complex - (E_NH3 + E_CO2)
    binding_energies.append(E_bind)
    print(f"N-C distance = {dist:.2f} Å, Binding Energy = {E_bind:.6f} Hartree")


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

complex_energies = np.array([
    -240.844828971281,
    -242.655750155489,
    -243.537346495117,
    -244.159866689913,
    -244.637576233054,
    -244.927046045637,
    -245.083617332531,
    -245.164433307442
])

E_NH3 = -56.5683081931929
E_CO2 = -188.669935659863

n_c_distances = np.linspace(1.8, 3.2, len(complex_energies))

binding_hartree = complex_energies - (E_NH3 + E_CO2)

hartree_to_kjmol = 2625.4996
hartree_to_kcalmol = 627.509474
binding_kjmol = binding_hartree * hartree_to_kjmol
binding_kcalmol = binding_hartree * hartree_to_kcalmol

print("Distance(Å)   E_complex(Hartree)    Binding(Hartree)    Binding(kJ/mol)   Binding(kcal/mol)")
for d, E_c, b_h, b_kj, b_kcal in zip(n_c_distances, complex_energies, binding_hartree, binding_kjmol, binding_kcalmol):
    print(f"{d:6.2f}        {E_c:14.6f}        {b_h:12.6f}        {b_kj:12.2f}        {b_kcal:12.2f}")

min_idx = np.nanargmin(binding_kjmol)
min_dist = n_c_distances[min_idx]
min_bind_kj = binding_kjmol[min_idx]
min_bind_kcal = binding_kcalmol[min_idx]

print("\nBest binding (minimum):")
print(f"  Distance = {min_dist:.2f} Å")
print(f"  Binding = {min_bind_kj:.2f} kJ/mol   ({min_bind_kcal:.2f} kcal/mol)")

# رسم
plt.figure(figsize=(7,4))
plt.plot(n_c_distances, binding_kjmol, 'o-', label='Binding energy (kJ/mol)')
plt.axhline(0, color='gray', linestyle='--')
plt.scatter([min_dist], [min_bind_kj], color='red', zorder=5, label=f"Min = {min_bind_kj:.2f} kJ/mol at {min_dist:.2f} Å")
plt.xlabel("N–C distance (Å)")
plt.ylabel("Binding energy (kJ/mol)")
plt.title("NH3–CO2 Binding Energy vs N–C distance")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


In [ ]:
# Save results for quantum simulation
print("Saving results for quantum simulation...")
np.savez('pes_scan_results.npz',
         distances=n_c_distances,
         energies=energies,
         min_distance=n_c_distances[min_idx],
         min_energy=energies[min_idx])

print("Classical PES scan completed successfully!")
print(f"Minimum energy found at N-C distance: {n_c_distances[min_idx]:.3f} Å")
print(f"Minimum energy: {energies[min_idx]:.6f} Hartree")

In [ ]:
from pyscf import gto, dft
from pyscf.geomopt.geometric_solver import optimize

mol = gto.M(
    atom = '''
    N   0.000000   0.000000   0.100000
    H   0.000000   0.9395    0.000000
    H   0.8137   -0.4697    0.000000
    H  -0.8137   -0.4697    0.000000
    ''',
    basis = 'def2-SVP'
)
mol.build()

mf = dft.RKS(mol)
mf.xc = 'b3lyp'
mol_opt = optimize(mf, maxsteps=200)
print("Optimized coordinates:\n", mol_opt.atom_coords())


In [ ]:
from pyscf.hessian import thermo

analysis = thermo.harmonic_analysis(mol, hess)
print(type(analysis))
print(analysis)


In [ ]:
from pyscf.hessian import thermo

analysis = thermo.harmonic_analysis(mol, hess)

print("Available keys in analysis:", analysis.keys())



In [ ]:
from pyscf.hessian import thermo

analysis = thermo.harmonic_analysis(mol, hess)

freqs = analysis['freq_wavenumber']

print("Frequencies (cm^-1):")
print(freqs)


In [ ]:
from pyscf import gto, dft

# Example: NH3
mol = gto.Mole()
mol.atom = '''
N  0.0000  0.0000  0.0000
H  0.0000  0.9395  0.0000
H  0.8137 -0.4697  0.0000
H -0.8137 -0.4697  0.0000
'''
mol.basis = 'def2-TZVP'
mol.build()

mf = dft.RKS(mol)
mf.xc = 'b3lyp'
mf.kernel()

# Hessian
hess = mf.Hessian().kernel()

# Get frequencies (in cm-1)
import numpy as np
from pyscf.hessian import thermo

from pyscf.hessian import thermo

analysis = thermo.harmonic_analysis(mol, hess)

# ترددات بالـ cm^-1
freqs_cm = analysis['freq_wavenumber']

print("Frequencies (cm-1):")
print(freqs_cm)

print("Frequencies (cm-1):")
print(freqs)


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from pyscf import gto, scf

def build_complex(R):
    mol = gto.Mole()
    mol.atom = f'''
    C 0.0 0.0 0.0
    O 0.0 0.0 1.16
    O 0.0 0.0 -1.16
    N 0.0 0.0 {R}
    H 0.0 0.94 {R+0.3}
    H 0.81 -0.47 {R+0.3}
    H -0.81 -0.47 {R+0.3}
    '''
    mol.basis = "sto-3g"
    mol.build()
    return mol

energies = []
distances = np.linspace(2.0, 5.0, 10)
for R in distances:
    mol = build_complex(R)
    mf = scf.RHF(mol).run()
    energies.append(mf.e_tot)

hartree_to_kcal = 627.509
energies_kcal = [(E - min(energies)) * hartree_to_kcal for E in energies]

plt.plot(distances, energies, marker='o', label="Energy (Hartree)")
plt.xlabel("Distance (Å)")
plt.ylabel("Energy (Hartree)")
plt.legend()
plt.show()

plt.plot(distances, energies_kcal, marker='s', color="red", label="Relative Energy (kcal/mol)")
plt.xlabel("Distance (Å)")
plt.ylabel("Energy (kcal/mol)")
plt.legend()
plt.show()

import pandas as pd
df = pd.DataFrame({"Distance (Å)": distances, "Energy (Hartree)": energies, "Relative Energy (kcal/mol)": energies_kcal})
print(df)


In [ ]:
# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt
from pyscf import gto, scf, dft

# ثوابت فيزيائية
kB = 1.380649e-23           # J/K
h = 6.62607015e-34          # J s
Na = 6.02214076e23          # 1/mol
c = 299792458.0             # m/s
R = 8.31446261815324        # J/(mol K)
hartree_to_joule = 4.3597447222071e-18   # J
hartree_to_kjmol = hartree_to_joule * Na / 1000.0
hartree_to_kcalmol = hartree_to_joule * Na / 4184.0
amu_to_kg = 1.66053906660e-27

# كتل الذرات
atomic_masses_amu = {
    'H': 1.00782503223,
    'C': 12.0,
    'N': 14.00307400443,
    'O': 15.99491461957
}

# ===============================
# دوال مساعدة
# ===============================

def guess_symmetry_number(mol):
    symbols = [mol.atom_symbol(i) for i in range(mol.natm)]
    if symbols.count('N')==1 and symbols.count('H')==3:
        return 3
    if symbols.count('C')==1 and symbols.count('O')==2:
        return 2
    return 1

def molecule_mass_kg(mol):
    masses = [atomic_masses_amu.get(mol.atom_symbol(i), 12.0) for i in range(mol.natm)]
    return sum(masses) * amu_to_kg

def principal_moments_kgm2(mol):
    coords = mol.atom_coords() * 1.0e-10  # Å -> m
    masses = np.array([atomic_masses_amu.get(mol.atom_symbol(i), 12.0) for i in range(mol.natm)]) * amu_to_kg
    cm = np.sum(coords * masses[:,None], axis=0) / np.sum(masses)
    r = coords - cm
    I = np.zeros((3,3))
    for i in range(mol.natm):
        m = masses[i]
        I += m * (np.dot(r[i], r[i]) * np.eye(3) - np.outer(r[i], r[i]))
    eigvals = np.linalg.eigvalsh(I)
    eigvals.sort()
    return eigvals

def is_linear(mol, tol_ratio=1e-3):
    I = principal_moments_kgm2(mol)
    if I[0] < tol_ratio * max(I[1], I[2]):
        return True
    return False

def extract_pos_freqs_from_analysis(analysis):
    freqs = np.array(analysis['freq_wavenumber'], dtype=complex)
    pos = []
    for f in freqs:
        if np.iscomplex(f):
            if abs(f.imag) > 1e-6:
                continue
            f = f.real
        if f > 1.0:
            pos.append(float(f))
    return np.array(pos)

def thermo_from_analysis(mf, mol, analysis, T=298.15, P=101325.0, sigma_override=None):
    """
    حساب الخصائص الحرارية للجزيء: طاقة حرارية، انتروبي، Gibbs
    """
    # استخراج الترددات
    freqs = extract_pos_freqs_from_analysis(analysis)
    # عدد الاهتزازات
    Nvib = len(freqs)

    # ثابت الغاز
    kbJ = kB  # J/K

    # طاقة اهتزازية لكل تردد
    energies = h * c * 100 * freqs  # تحويل cm^-1 -> J

    # طاقة اهتزازية متوسطة لكل اهتزاز
    ZPE = 0.5 * np.sum(energies)  # J

    # الانتروبي والحرارة النوعية (تقريب هارمونك)
    vibrational_contrib = energies / (kbJ * T)
    S_vib = R * np.sum(vibrational_contrib / (np.exp(vibrational_contrib) - 1) - np.log(1 - np.exp(-vibrational_contrib)))

    # الطاقة الداخلية
    U_vib = np.sum(energies / (np.exp(vibrational_contrib) - 1) + 0.5 * energies)  # J

    # طاقة Gibbs الحرارية
    G = U_vib - T * S_vib  # J

    return {'ZPE': ZPE, 'S_vib': S_vib, 'U_vib': U_vib, 'G': G}

# ===============================
# مثال: NH3 + CO2
# ===============================

def build_complex(R):
    mol = gto.Mole()
    mol.atom = f'''
    C 0.0 0.0 0.0
    O 0.0 0.0 1.16
    O 0.0 0.0 -1.16
    N 0.0 0.0 {R}
    H 0.0 0.94 {R+0.3}
    H 0.81 -0.47 {R+0.3}
    H -0.81 -0.47 {R+0.3}
    '''
    mol.basis = "sto-3g"
    mol.build()
    return mol

# ===============================
# مسح الطاقة
# ===============================
distances = np.linspace(2.0, 5.0, 10)
energies = []

for R in distances:
    mol = build_complex(R)
    mf = scf.RHF(mol).run()
    energies.append(mf.e_tot)

hartree_to_kcal = 627.509
energies_kcal = [(E - min(energies)) * hartree_to_kcal for E in energies]

# رسم منحنى الطاقة
plt.figure(figsize=(7,4))
plt.plot(distances, energies_kcal, 'o-', color='red', label="Relative Energy (kcal/mol)")
plt.xlabel("Distance N-C (Å)")
plt.ylabel("Energy (kcal/mol)")
plt.title("NH3–CO2 Energy vs N-C distance")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# طباعة النتائج
import pandas as pd
df = pd.DataFrame({"Distance (Å)": distances, "Energy (Hartree)": energies, "Relative Energy (kcal/mol)": energies_kcal})
print(df)
